### PR TITLE
Use chockidar instead of gaze

### PR DESCRIPTION
**Pull request by piteer1**
Chokidar handles native FS events better than gaze. This makes development possible under docker on OSX.

### CODE REVIEW

**Comment by piteer1** [comment]
Hello,

After merge master branch to `feature/react-intl` there will be still a gaze depencency in `tools/extractMessages.js`. Should I make a separate PR to remove gaze on that branch also or you will resolve it when syncing branches?

**Comment by frenzzy** [comment]
@piteer1 thanks! I think @langpavel will be able to update the branch during next rebasing on master, I am right?

**Comment by langpavel** [comment]
Thanks,I should review more precisely this, but it's sometimes hard :-)

**Comment by langpavel** [comment]
Btw @koistya, @frenzzy, what about merging PRs to master, can we agree on if all of us approve PR, last of us should merge?

**Comment by frenzzy** [comment]
Good suggestion, I don't mind

**Comment by langpavel** [comment]
Hi @piteer1, merged to feature branches as well

**Pull request merged**
