### PR TITLE
Remove outdated instructions regarding WebStorm integration.

### LINKED ISSUE #1265: Webstorm IDE Integration dead link in quickstart
The Webstorm IDE integration link in the [Quick Start](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md#quick-start) points at https://www.jetbrains.com/webstorm/help/create-new-project-react-starter-kit.html, which is a 404.

I have found JetBrains docs for creating a new project based on this boiler plate, but they are outdated.

https://www.jetbrains.com/help/webstorm/2017.1/generating-a-project-from-a-framework-template.html#d88767e51

Since these docs were written, they have added more templates, but have removed the template based on this project in favor of the official `create-react-app` setup.

image

### PR DESCRIPTION
**Pull request by ckeeney**
This closes #1265

### CODE REVIEW

**Comment by langpavel** [comment]
Outdated

**Comment by ckeeney** [comment]
This should really be merged in instead of closed.  The instructions are outdated and this pull request removes the outdated instructions.

**Comment by langpavel** [comment]
Okay, thanks for reaction :-) Can you update info or create new PR, please? Thanks!

**Comment by ckeeney** [comment]
Sorry, update what info?  I don't think there are any specific instructions for integration with WebStorm.

**Comment by langpavel** [comment]
@ckeeney Sorry, not info, entire PR, there is conflict so it cannot be merged without fixing conflict..

**Comment by ckeeney** [comment]
Okay I will do so soon.  I'm not at a computer right now.

**Comment by ckeeney** [comment]
Sorry it took 4 days for me to look at this and close it anyways.

The conflict was because a nearly identical change has already been made.

**Pull request closed without merging**
