### PR TITLE
Updated Post-css loader version

### PR DESCRIPTION
**Pull request by chentaixu**
Now post-css is version 0.6.0

### CODE REVIEW

**Comment by koistya** [comment]
Hey, thanks! The last time I checked the `postcss-loader v6.0.0` wasn't compatible with some of the PostCSS plugins we're using.. but I will check again.

**Comment by chentaixu** [comment]
@koistya You're right! Hold on a sec till you merge...

**Comment by chentaixu** [comment]
Yep. A lot is going on right now. Autoprefixer-core is deprecated, cssnext will probably be merged into core functionality of postcss, etc etc

**Comment by koistya** [comment]
cssnext CLI might be depricated in favor of postcss-cssnext plugin

**Pull request closed without merging**
