### PR TITLE
Update mkdirp to 1.0.3

### PR DESCRIPTION
**Pull request by mehdiraized**

### CODE REVIEW

**Comment by piglovesyou** [comment]
Thank you.

* We can avoid sync functions, can't we?
* Why don't we drop Node v8 support here, mkdirp@1.x expects Node > v10 and  it's out of maintained now

**Comment by mehdiraized** [comment]
> Thank you.
> 
> * We can avoid sync functions, can't we?
> * Why don't we drop Node v8 support here, [mkdirp@1.x](mailto:mkdirp@1.x) expects Node > v10 and  it's out of maintained now

it's ok ;)

**Comment by piglovesyou** [comment]
Ah, what's ok?

**Comment by ulani** [comment]
@mehdiraized  thank you very much for this PR! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Pull request closed without merging**
