### PR TITLE
TRACKING: master → feature/apollo-pure

### PR DESCRIPTION
**Pull request by langpavel**
Pure [Apollo](https://www.apollographql.com/) integration based on `master`.

## Features

* TypeScript implementation of RSK that Apollo primarily supports
* `apollo-client` with full server-side rendering - No `fetch()`
* Client-side state management with `apollo-client@2.5` with `networkStatus` example
* `apollo-server` serves GraphQL API
* Codegen - TypeScript checking for GraphQL response according to GraphQL Schema
* GraphQL Scalar type - `Timestamp` for an example

### CODE REVIEW

**Comment by piglovesyou** [comment]
I wrote [a blog post](https://dev.to/piglovesyou/learning-apollo-toolset-with-react-starter-kit-fo8)

**Comment by piglovesyou** [comment]
I found @koistya fully rebased the project. @langpavel and I (and a lot more) aren't listed as [contributors](https://github.com/kriasoft/react-starter-kit/graphs/contributors) anymore😇

**Comment by koistya** [comment]
@piglovesyou @langpavel the codebase was re-written from scratch on the orphan `main` (now default) branch, while v1 is still available on the `master` branch (because it was not updated for a long time). Since GitHub doesn't count contributions from non-default branches let's have you listed in the README file instead.

**Comment by koistya** [comment]
@piglovesyou @piglovesyou here you go https://github.com/kriasoft/react-starter-kit#contributors-

**Pull request closed without merging**
