### PR TITLE
TRACKING: feature/redux → feature/apollo

### PR DESCRIPTION
**Pull request by langpavel**
- [x] Apollo client mounted on existing redux store
- [x] Data are automatically prefetched on server, **no imperative code in router**
- [x] ***Direct* server side GraphQL** - no additional HTTP request on SSR
- [x] GraphQL queries are pre-parsed by Webpack loader
- [x] Demonstrated on Home route/component

### CODE REVIEW

**Comment by stubailo** [comment]
Just looked over everything, this looks awesome - is there anything in particular you would want more feedback on?

**Comment by langpavel** [comment]
@stubailo Feedback is welcomed, but this is feature branch.
It should be for reference. When I came to RSK I feel it should cover more advanced topics. It still appears around. I'm happy with this but I feel more people wants more.. On other side, I want people knowing *why* this..

**Comment by stubailo** [comment]
Ah, OK - so the idea is to keep it open as an example for how to do a certain thing, but not merge it?

I'd be happy to help provide some content about what this is doing, or help add some more advanced features.

**Comment by langpavel** [comment]
@stubailo I'm using this in production on two small sites, I'm back-pushing features there.. I love learning and  feedback

**Comment by tim-soft** [comment]
First of all, this is an awesome boilerplate

Poking around in the code has brought up a few questions
1. Why go with [graphql/express-graphql](https://github.com/graphql/express-graphql) over [apollographql/graphql-server](https://github.com/apollographql/graphql-server), which seems to pair really nicely with the Apollo Client?

Which brings up my next question

2. Apollo client supports subscriptions, shouldn't the apollo client feature branch be exemplary of this feature? (I may be mistaken, but I do not believe it is in here)

Thank you for your hard work!

**Comment by langpavel** [comment]
@tim-soft Hi, Thanks!

> Why go with graphql/express-graphql over apollographql/graphql-server, which seems to pair really nicely with the Apollo Client?

This is because RSK master have simple GraphQL server already configured.
I'm trying avoid any unnecessary diversity between branches, it makes maintenance easier and cleaner.
I believe it is not too much work to switch on server from express to Apollo..

> Apollo client supports subscriptions, shouldn't the apollo client feature branch be exemplary of this feature? (I may be mistaken, but I do not believe it is in here)

Create wrong example of subscriptions is very easy. If I implement subscriptions, I have to choose right backend for pub-sub (Redis, RabbitMQ, Postgres or some online service?) and handle ACL and much more..
I believe that advanced users will take this really seriously and implement this by they own needs.
All what I can try implement here can be only one shared channel with stupid component on the client side, say something like currently online users on site without well scalable server. I think this is not what users want in starter, many of them will probably want disable subscriptions until they really need them — so HOWTO can be better fit then delivering naïve implementation which open mostly unused websocket for every connected client...

**Comment by stubailo** [comment]
Yeah, I don't think either of those are necessary for a good boilerplate, express-graphql is just fine. But we are working on creating a production-ready subscriptions example for people to go along with the work in the GraphQL specification.

**Comment by charyorde** [comment]
@langpavel I specifically work off the `feature/redux` branch. And want to continue that way cos I see that you keep the `feature/redux` branch well updated with master. Please keep that up. 👍 

Now I want to use the `subscription` feature (client only). How would you suggest I work with the `feature/apollo` branch? I would have loved that you merged `feature/apollo` into `feature/redux`. :)

**Comment by langpavel** [comment]
Hi @charyorde 
Just simply try merge `feature/apollo` branch to your codebase. I'm trying keep all synced this way:
`master` → `feature/redux` → `feature/apollo` → `feature/react-intl`
Subscriptions are not there but you can patch your client code, and you should integrate it on server too.

**Comment by gilbox** [comment]
In `src/routes/home/index.js` you can remove the `fetch`-news-related code. Did you keep it in on purpose?

**Comment by leviwheatcroft** [comment]
@charyorde @langpavel thinking about playing around with subscriptions too..

**Comment by tim-soft** [comment]
@leviwheatcroft Where things get a little more complex/opinionated with subscriptions is a pub/sub system. Something like Redis is a very big dependency and the Websocket server should be it's own app imo

**Comment by piglovesyou** [comment]
@langpavel This is the best combination of the web frontend of the time I feel, I was inspired from this branch a lot. Thanks.

Thing is, Apollo Client now does not have to depend on Redux since it has its own caching mechanism. [The official docs](https://www.apollographql.com/docs/react/why-apollo.html#case-studies) points to [this blog post](https://dev-blog.apollodata.com/reducing-our-redux-code-with-react-apollo-5091b9de9c2a?_ga=2.78143060.1751369483.1530659361-666528664.1529022451).

So what do you think when I say `feature/apollo` can only based on `master`, instead of `feature/redux`? That will push efficiency and simplicity of the boilerplate forward, I believe.

But yeah `feature/react-intl` is a dependant of `feature/apollo` and things are a little complicated. Then I think I also can push a new `feature/apollo-pure` or something.

**Comment by tim-soft** [comment]
@piglovesyou I'm not sure what you mean... Apollo client isn't relying on Redux at all.
https://github.com/kriasoft/react-starter-kit/pull/1147/commits/a65988a15c7b03df88534cc053431c57e9b5a0f6

**Comment by jatinnn** [comment]
Would have been nice if feature/apollo was based on master rather then feature/redux.

**Comment by langpavel** [comment]
@piglovesyou `feature/apollo-pure` sounds great. But I'm sorry, I have no time to do this in near future

**Comment by piglovesyou** [comment]
@langpavel Good to hear that.

I'm really interested in doing it using `apollo-link-state` and `apollo-server`, but I cannot promise starting it soon（´-｀;）

**Comment by piglovesyou** [comment]
https://github.com/kriasoft/react-starter-kit/pull/1664

I created a PR of a pure Apollo branch called `feature/apollo-pure`. Basically I just introduced

* `apollo-link-state`
    * with initial state sharing between server and client
    * with `networkState` example
* `apollo-server`

**without**

* `redux`
* Fetch function in a context, since `apollo-client` will take care of it

upon the `master` branch, by picking some codebase from `feature/apollo`. I really appreciate a quick review from the Apollo-interested engineers around.

**Comment by langpavel** [comment]
@piglovesyou, nice nickname :rofl:
Great work! Thank you! Let's discuss more in #1664

**Comment by montoya332** [comment]
should these be closed since they are outdated

**Pull request closed without merging**
