### PR TITLE
Fix IE<10 history api (fix exception on missing replaceState & pushState)

### PR DESCRIPTION
**Pull request by artemkaint**
This change is [Reviewable](https://reviewable.io/reviews/kriasoft/react-starter-kit/204)

### CODE REVIEW

**Comment by koistya** [comment]
@artemkaint thanks for the PR. I need some time to verify it.

**Comment by Bogdaan** [comment]
`window.history` in ie<10 is undefined.

Maybe better use:
```
window.location.href = path;
```

**Comment by langpavel** [comment]
Uff. Is this still actual?

**Comment by artemkaint** [comment]
IE<11 isn't supported yet. I suppose the ticket is obsolete

**Pull request closed without merging**
