### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by 7anshuai**

### CODE REVIEW

**Comment by piglovesyou** [comment]
* Glad if you show us the error log without it. Was it broken?
* Let's choose one from [the LTSs](https://nodejs.org/en/about/releases/) if we're going to change the Node version. Node v8 is out of support now

**Comment by 7anshuai** [comment]
Docker build log:

```bash
Sending build context to Docker daemon  553.2MB
Step 1/11 : FROM node:8.10.0-alpine
 ---> adc4b0f5bc53
Step 2/11 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 16916f32d7a2
Step 3/11 : COPY ./build/package.json .
 ---> b37f0899a2c1
Step 4/11 : COPY ./build/yarn.lock .
 ---> f6682be77aec
Step 5/11 : RUN yarn install --production --no-progress
 ---> Running in 96df184313e9
yarn install v1.5.1
[1/5] Validating package.json...
error @: The engine "node" is incompatible with this module. Expected version ">=8.16.2".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install --production --no-progress' returned a non-zero code: 1
[20:05:53] Finished 'build' after 29865 ms
✨  Done in 32.26s.
```

Run `yarn install` expected version ">=8.16.2"

**Comment by piglovesyou** [comment]
See, it's from f5c052f016734ca83d436bb9b829f5fab5958f13 . And the sequelize error might come from [the recent updates](https://github.com/kriasoft/react-starter-kit/pull/1751).

@7anshuai Thank you!

**Comment by karanp41** [comment]
Hello @7anshuai 
I'm getting following error while deploying in 3rd step:
`2020-01-24 11:38:31    ERROR   Failed to build Docker image aws_beanstalk/staging-app: 7d
Step 3/9 : COPY ./build/package.json .
COPY failed: stat /var/lib/docker/tmp/docker-builder168800563/build/package.json: no such file or directory. `
Any idea?

Thanks in advance!

**Comment by 7anshuai** [comment]
@karanp41 Does the file `./build/package.json` exist in the path where you're starting the build from?

**Comment by karanp41** [comment]
No, initially there is no such file in the build folder but the file is in the root of the project. @7anshuai

**Comment by karanp41** [comment]
@7anshuai Do I need to copy it manually from root to somewhere?

**Comment by 7anshuai** [comment]
> @7anshuai Do I need to copy it manually from root to somewhere?

Run `yarn build --release --docker`  will create the `build` folder and copy static files to the output folder.
See [this](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md#how-to-build-test-deploy).

**Pull request merged**
