### PR TITLE
Add --static flag to build script which allows to generate static html for specific routes

### PR DESCRIPTION
**Pull request by frenzzy**
```shell
$ npm run build -- --static --release
```
Build folder with static html files

refs #61 #156 #260 #634 #635

### CODE REVIEW

**Comment by Dmitry-N-Medvedev** [comment]
oh, please, accept this :)

**Comment by Dmitry-N-Medvedev** [comment]
A question: is it possible to generate static version so that index.html gets generated as well?

**Comment by frenzzy** [comment]
```js
const routes = [
  '/page',       // => build/public/page.html
  '/page/',      // => build/public/page/index.html
  '/page/name',  // => build/public/page/name.html
  '/page/name/', // => build/public/page/name/index.html
];
```

**Comment by srinivasdamam** [comment]
@frenzzy what about the routes that have params?

**Comment by frenzzy** [comment]
You can specify the same route multiple times with all available params manually
```js
const routes = [
  // ...
  '/product/iphone-7',            // => build/public/product/iphone-7.html
  '/product/iphone-7/specs',      // => build/public/product/iphone-7/specs.html
  '/product/galaxy-note-7',       // => build/public/product/galaxy-note-7.html
  '/product/galaxy-note-7/specs', // => build/public/product/galaxy-note-7/specs.html
  // etc.
];
```

Or you can dynamically build such routes based on list of params from api or somewhere else
```js
async function render() {
  let server;
  await new Promise(resolve => (server = runServer(resolve)));

  // add dynamic routes
  const products = await fetch(`http://${host}/api/products`).then(res => res.json());
  products.forEach(product => routes.push(
    `/product/${product.uri}`,
    `/product/${product.uri}/specs`
  ));

  await routes.reduce(/* ... */);
  server.kill('SIGTERM');
}
```

**Pull request merged**
