### PR TITLE
add google auth

### PR DESCRIPTION
**Pull request by alexsuslov**
You need to change the settings by Google auth.

### CODE REVIEW

**Comment by langpavel** [comment]
@koistya, @frenzzy I think this is useful piece of code. Do you think it should be merged to master? If so, I can help @alexsuslov rebase it

**Comment by advance512** [comment]
+1, this is very useful.
I also suggest a tutorial on adding new strategies (though the commit is quite clear).

**Comment by zirho** [comment]
I was wondering why this is not implemented. I'm waiting for this to be merged. 
We may want to update README.md or any docs related to Oauth materials.

**Comment by ulani** [comment]
@alexsuslov  thank you very much for this PR! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Pull request closed without merging**
