### PR TITLE
Feature/semanticui

### PR DESCRIPTION
**Pull request by ahmdilloo**
Hi
I added semantic ui to this project and use it in header and login page. i think maybe some one need this and can quickly use it.
like this: [#499](https://github.com/kriasoft/react-starter-kit/issues/499)

### CODE REVIEW

**Comment by tim-soft** [comment]
Why not install semantic-ui to `node_modules`?

**Comment by zocky** [comment]
@tim-soft - That only installs the js. Css still needs to be installed with the semantic-ui-css package. The semantic-ui-react instructions then say that the css should be imported using `import 'semantic-ui-css/semantic.min.css';` in index.js (which I suppose is client.js). This doesn't have the intended effect though.

How should that be done?

**Comment by kalin-mv** [comment]
Hi,
please try this:

`yarn add semantic-ui-css`

**Layout.js**
```
import g from '../../../node_modules/semantic-ui-css/semantic.min.css';
import s from './Layout.css';

class Layout extends React.Component {
}

export default withStyles(g, s)(Layout);
```

**Comment by tim-soft** [comment]
@kalin-mv this is a bad idea as it will inline a very, very large amount of CSS into your JS which gets sent to the client in one large chunk.

The better approach imo would be to use some webpack loader for the styles in combination with extract-text-plugin, mostly because of how absolutely large semantic-ui resources can be. Doing it this way would allow semantic css to get downloaded _in parallel_ to JS as it's own file, get cached by the browser and not bottleneck JS loading/execution.

**Comment by langpavel** [comment]
As a PR this is really bad idea.. and outdated.
Everybody reaching this, please follow @kalin-mv's example

**Comment by langpavel** [comment]
@kranz It depends.. If semantic-ui-css uses jquery only in `componentDidMount` and didn't try do anything on server, it should be OK

**Comment by kranz** [comment]
@langpavel please apologize. I should have posted this question in semantic-ui-react...

**Pull request closed without merging**
