### PR TITLE
Upgrade Babel to v6.x

### PR DESCRIPTION
**Pull request by koistya**
- [x] Update Babel from v5.x to v6.x
- [x] Configure ES2015, React, and State-0 presets (see `.babelrc`)
- [x] Update React Transform to v2.0.0 (compatible with Babel v6.x)
- [x] Replace `import 'babel-core/polyfill'` with `import 'babel-polyfill'`
- [x] Remove ES2015 decorators since Babel v6.x doesn't support them yet
- [x] Add `transform-runtime` plugin in `.babelrc`
- [x] Update CommonJS imports to comply with Babel v6.x (e.g. `require('./class.js').default)`)
- [x] Update `tools/run.js` to make it work with Babel CLI v6.x
- [ ] Need to find and fix the issues related to this upgrade.

### CODE REVIEW

**Comment by dfrankland** [comment]
I am getting errors like the following when using `npm start` on Ubuntu 15.10:
```bash
Warning: a promise was created in a  handler but was not returned from it
    at _callee$ (/media/dylan/Shared/repos/react-starter-kit/build/webpack:/src/api/content.js:44:28)
    at tryCatch (/media/dylan/Shared/repos/react-starter-kit/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/media/dylan/Shared/repos/react-starter-kit/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/media/dylan/Shared/repos/react-starter-kit/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at step (/media/dylan/Shared/repos/react-starter-kit/build/server.js:3404:204)
From previous event:
    at step (/media/dylan/Shared/repos/react-starter-kit/build/server.js:3404:354)
    at /media/dylan/Shared/repos/react-starter-kit/build/server.js:3404:447
From previous event:
    at /media/dylan/Shared/repos/react-starter-kit/build/server.js:3404:101
    at /media/dylan/Shared/repos/react-starter-kit/build/webpack:/src/api/content.js:51:2
    at Layer.handle [as handle_request] (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/layer.js:95:5)
    at next (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/layer.js:95:5)
    at /media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/index.js:330:12)
    at next (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/index.js:176:3)
    at router (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/index.js:312:13)
    at /media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/index.js:330:12)
    at next (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/node_modules/serve-static/index.js:120:7)
    at SendStream.EventEmitter.emit (events.js:95:17)
    at SendStream.error (/media/dylan/Shared/repos/react-starter-kit/node_modules/express/node_modules/send/index.js:245:17)
```

**Comment by dfrankland** [comment]
Seems like Babel 6 is not playing well with Bluebird Promises: https://github.com/babel/babel-loader#custom-polyfills-eg-promise-library

**Comment by dfrankland** [comment]
`Link.js` has issues because `this` is getting called from a top level. In Babel 6's strict mode, top level `this` is `undefined`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Securing_JavaScript
http://blog.jesusgollonet.com/2015/04/21/this-undefined-es6-arrow-functions/

**Comment by dfrankland** [comment]
Decorators can be added using a legacy package: http://stackoverflow.com/questions/33801311/webpack-babel-6-es6-decorators

**Comment by koistya** [comment]
@dfrankland cool, thanks! Checking...

**Comment by ericvera** [comment]
I think docs/react-style-guide.md also needs to be updated to reflect the withStyles change.

**Pull request merged**
