### PR TITLE
TRACKING: feature/redux → feature/react-intl

### PR DESCRIPTION
**Pull request by langpavel**
This will not be closed. This is tracking PR for keeping feature branches in sync:

See #1084  — `master` → `feature/redux`
See #1136  — `master` → `feature/react-intl`

### CODE REVIEW

**Comment by Borales** [comment]
@langpavel thanks for your PR! 
Is there a plan to update this branch?

I'm using this branch as my app skeleton. I've started with master branch (since it was on React v15.x), and went through `master` => `feature/redux` => `feature/apollo` => `feature/react-intl`.

After the recent commits to the master branch (Babel 7, React 16) - I've started to get an error, but I can't figure out how to get it fixed, maybe you have some thoughts.

(no custom code, just clean clone from this repo and 3 merges).

```
ERROR in ./src/server.js
Module build failed: TypeError: ~/react-starter-kit/src/server.js: file.has is not a function
    at PluginPass.pre (~/react-starter-kit/node_modules/babel-plugin-react-intl/lib/index.js:199:23)
    at File.transform (~/react-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:475:20)
    at ~/react-starter-kit/node_modules/babel-core/lib/transformation/pipeline.js:54:17
    at File.wrap (~/react-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:501:14)
    at Object.transform (~/react-starter-kit/node_modules/babel-core/lib/transformation/pipeline.js:51:15)
    at transpile (~/react-starter-kit/node_modules/babel-loader/lib/index.js:50:20)
    at ~/react-starter-kit/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (~/react-starter-kit/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
 @ multi babel-polyfill ./src/server.js
[23:44:19] Failed to compile 'server' after 869 ms
(node:98436) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Compilation failed!
Time: 13792ms
 2 assets

ERROR in ./src/clientLoader.js
Module build failed: TypeError: ~/react-starter-kit/src/clientLoader.js: file.has is not a function
    at PluginPass.pre (~/react-starter-kit/node_modules/babel-plugin-react-intl/lib/index.js:199:23)
    at File.transform (~/react-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:475:20)
    at ~/react-starter-kit/node_modules/babel-core/lib/transformation/pipeline.js:54:17
    at File.wrap (~/react-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:501:14)
    at Object.transform (~/react-starter-kit/node_modules/babel-core/lib/transformation/pipeline.js:51:15)
    at transpile (~/react-starter-kit/node_modules/babel-loader/lib/index.js:50:20)
    at ~/react-starter-kit/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (~/react-starter-kit/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
 @ multi babel-polyfill ./tools/lib/webpackHotDevClient ./src/clientLoader.js
[23:44:32] Failed to compile 'client' after 13789 ms
Error: Compilation failed!
    at Compiler.<anonymous> (~/react-starter-kit/tools/start.js:47:16)
    at Compiler.applyPlugins (~/react-starter-kit/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (~/react-starter-kit/node_modules/webpack/lib/Compiler.js:104:17)
    at onCompiled (~/react-starter-kit/node_modules/webpack/lib/Compiler.js:54:18)
    at applyPluginsAsync.err (~/react-starter-kit/node_modules/webpack/lib/Compiler.js:514:14)
    at next (~/react-starter-kit/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (~/react-starter-kit/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (~/react-starter-kit/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (~/react-starter-kit/node_modules/webpack/lib/Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (~/react-starter-kit/node_modules/tapable/lib/Tapable.js:195:46)
error Command failed with exit code 1.
```

**Comment by langpavel** [comment]
@Borales Hi, sure, give me few days

**Comment by Borales** [comment]
@langpavel I checked `~/react-starter-kit/node_modules/babel-plugin-react-intl/lib/index.js:198` file (https://github.com/yahoo/babel-plugin-react-intl/blob/master/src/index.js#L180). 

If I comment out `file.has` part - the code works (although not really sure for 100%).

```
pre: function pre(file) {
  // if (!file.has(MESSAGES)) {
    file.set(MESSAGES, new _map2.default());
  //}
},
```

So the problem is in `file` object, I'd assume it should be an instance of `Map` object.

**Comment by Borales** [comment]
@langpavel any guesses?

**Comment by Borales** [comment]
@langpavel could you please let me know if you're doing something there or I should better try to fix it by myself?

**Comment by Borales** [comment]
@langpavel Related `babel-plugin-react-intl` issue - https://github.com/yahoo/babel-plugin-react-intl/issues/122

Related Babel PR - https://github.com/babel/babel/pull/6529

**Comment by Borales** [comment]
@langpavel babel/babel#6529 has been merged, waiting for the next beta releale

**Comment by langpavel** [comment]
Hi @Borales sorry, for unresponsiveness from my side. I'm very busy. Do you only wait for me or you can contribute with something?
Now I know that I cannot do update until 30th this month (2017-10-30) but I can spend two hours on reviewing new PR.

**Comment by langpavel** [comment]
@Borales Only merge needed?

**Comment by Borales** [comment]
@langpavel actually, no actions required from your side.

I've found the problem I had with this branch and `file.has` method inside of `babel-plugin-react-intl` plugin, I've submitted a PR to the Babel repo directly. The fix is on their master right now, so once they release a new beta - we have to update deps in `package.json` (`master` branch) and the problem will be solved.

Until next Babel beta - this branch remains broken(-ish, only if you are using latest `master` branch + pulls from `react-intl` branch).

**Comment by Borales** [comment]
@frenzzy https://github.com/babel/babel/releases/tag/v7.0.0-beta.5 has been released, can we update `master` branch?

cc @langpavel

**Comment by Borales** [comment]
@frenzzy sorry, false alarm, they still haven't published it to the NPM

**Comment by frenzzy** [comment]
@Borales see #1452

**Pull request closed without merging**
