### PR TITLE
separate gulpfile

### PR DESCRIPTION
**Pull request by tadjik1**
Hi there.
This pr trying to solve #56 

1. Separate gulpfile and create config file for common configs (eg autoprefixer).
2. Change eslintrc for tests (right now there are many errors about missin 'use strict').

### CODE REVIEW

**Comment by koistya** [comment]
@tadjik1 thanks for the PR! FYI, `styles` and `autoprefixer` stuff is going to be removed from the `gulpfile.js` (see #43), leaving just a few tasks related to firing up webpack, development web server. The `gulpfile.js` will be even smaller than it is now. Splitting it into separate files will add unnecessary complexity to the project's structure. Some folks go even farther and remove dependency on Gulp in favor of using just [webpack](https://webpack.github.io) and [npm scripts](https://docs.npmjs.com/misc/scripts).

**Comment by tadjik1** [comment]
Heh)
Actually I believe that gulp allows to do more complex thing with less pain than webpack. For example, sometimes you need to run some utilities task (like generating sitemap, or create zip archive with your project files, or deploy). As for me - I prefer using gulp for that.

**Comment by koistya** [comment]
Gulp doesn't play way with component-based UI development and generally should not be used for bundling your source code (unless you have a flat site structure without components). See:

- http://webpack.github.io/docs/stylesheets.html
- https://github.com/webpack/css-loader
- https://github.com/webpack/style-loader
- https://github.com/webpack/file-loader
- https://github.com/webpack/url-loader

**Comment by tadjik1** [comment]
ok

**Pull request closed without merging**
