### PR TITLE
Add react-router

### LINKED ISSUE #20: Use react-router
How do you feel about using [react-router](https://github.com/rackt/react-router) instead of a custom basic routing approach? It seems to be getting super popular and the fact that it's build for react makes me like it a lot more anyways

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5017972-use-react-router?utm_campaign=plugin&utm_content=tracker%2F1144755&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1144755&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jakecraige**
closes #20 

Since I already did this when playing around I figured I'd just submit the PR prior to discussion

### CODE REVIEW

**Comment by frankleng** [comment]
love this PR. @jakecraige  mind resolving the conflicts if you have time?

**Comment by goatslacker** [comment]
If there aren't any other large commits landing any time soon I'll rebase this and fix all merge conflicts.

**Comment by koistya** [comment]
One thing to consider: currently there is a global handler listening for `window.onclick` events, which fires `AppActions.navigateTo(...)`. This is done, in order to make internal links inside the content loaded dynamically from the server work fine (without full-page reload).

**Comment by frankleng** [comment]
@koistya one of the biggest bonus of switching to react-router is probably the out of box support for auth. Can you perhaps give an example of auth flow with the current Flux based router?

**Comment by jakecraige** [comment]
I'm not currently doing anything with react so I'd love for someone to take this over if they feel so inclined. @goatslacker ?

**Pull request closed without merging**
