### PR TITLE
Default response header Cache-Control to 1 day in production;disable response cache in __DEV__

### PR DESCRIPTION
**Pull request by buildbreakdo**
Default Cache-Control to 1 day in production (adjust per needs, 1 day is just a generic default pulled from Google's home page). When in `__DEV__` mode disable caching of responses. Issues are touched on in #1241 .

### CODE REVIEW

**Comment by koistya** [comment]
What if data API changed, and the prev. version of the JavaScript bundle can't handle it. I assume this technique must be combined with server version checking (via Ajax).

**Comment by buildbreakdo** [comment]
@koistya Intriguing question, according to this: http://stackoverflow.com/questions/23603023/file-caching-query-string-vs-last-modified (top answer last scenario) the RSK is already in best practice space. The url to the file changes. So there is nothing to manage on the RSK end, it is already managed by the bundling process through generating a new file name and thus a new url for that file.

All this does, is cache that response if it is asked for again. If the file URL changes then that will be a new response, and not pulled from the cache.

**Comment by buildbreakdo** [comment]
@koistya Confused by all the drinks I had, drinking and coding is not always the best of ideas, but it is fun!

Okay, what should be happening in a scenario where the API version changes and the prev version of the JavaScript bundle cannot handle it is API versioning. The API version would be hard coded into the client.js bundle via the URL, like `reddit.com/api/v1/friends` (https://www.reddit.com/dev/api/). If the a new version of the API is published, the old bundle that relies on a particular API version to work would still be targeting the old API version at `/api/v1` while the new version of the API would be published at `api/v2`. Personal preference is for URL based versioning, for the sake of simplicity and readability, plenty of religious discussions around that.

Alternatively, could publish a new client and API simultaneously to keep them in sync, which is what we traditionally do in most web app scenarios where the API is included in the same project (assuming you're talking about situations where the API has been externalized like https://github.com/kriasoft/nodejs-api-starter).

**Comment by ulani** [comment]
@buildbreakdo  thank you very much for this PR! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Pull request closed without merging**
