### PR TITLE
Replace universal router with react-router

### PR DESCRIPTION
**Pull request by djpark**
There's a lot of discussion around having a version of this starter kit that leverages react-router. This PR is a first stab at this and incorporates techniques used in @Bogdaan's [react-auth-kit](https://github.com/Bogdaan/react-auth-kit).  Look forward to hearing your feedback.  

Side note: @koistya has a [good article](https://medium.freecodecamp.com/you-might-not-need-react-router-38673620f3d#.koy29uedg) discussing the motivation for using universal-router.

### CODE REVIEW

**Comment by koistya** [comment]
Looks good, though I personally prefer not to mix data fetching logic with UI representation, this way you can load data and corresponding application chunk(s) to render that data in parallel, for example (in React Router and Webpack 2.0 syntax):

```js
{
  path: '/tasks/:id',
  getComponent(location, callback) {
    Promise.all([
      fetch(`/api/tasks/${location.params.id}`),
      System.import('./routes/tasks/TodoList'),
    ]).then(([tasks, Component]) => {
      callback(() => <Component tasks={tasks} />);
    }, callback);
  }
}
```

The issue with that approach is that routes will be pretty verbose in that case, that's the reason why all the routes are splitted into multiple files in RSK and then imported inside `/routes/index.js`.

**Comment by djpark** [comment]
Great points!  I'll have another chance to look at this over the weekend.  Stay tuned.

**Comment by FakhruddinAbdi** [comment]
@djpark any progress ?

**Comment by Ank49** [comment]
It could be great if you could update this feature/exemple with the present RSK, I've encountered several issues trying to put react-router in the actual project.. (started React a few weeks ago, my bad) 👍🏻

**Comment by okendoken** [comment]
Hi guys,

please take a look at [react-dashboard](https://github.com/flatlogic/react-dashboard). We forked it from React Starter Kit and integrated react-router & bootstrap. We plan to continuously update it.

Best

**Comment by ulani** [comment]
@djpark  thank you very much for this PR! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Pull request closed without merging**
