### PR TITLE
ApolloClient/createNetworkInterface credentials

### PR DESCRIPTION
**Pull request by mika75**
To pass basic auth

createApolloClient.client.js

```
const client = new ApolloClient({
  networkInterface: createNetworkInterface({
    uri: '/graphql',
    opts: {
	    credentials: 'include',
    },
  }),
  queryDeduplication: true,
  reduxRootSelector: state => state.apollo,
});

export default function createApolloClient() {
  return client;
}
```

### CODE REVIEW

**Comment by langpavel** [comment]
@mika75 Thanks! But is commit reflecting what you propose? :-)

**Comment by mika75** [comment]
@langpavel Thank !

**Comment by GGAlanSmithee** [comment]
BTW, here are the `credentials` options;

* omit: Never send cookies.
* same-origin: Only send cookies if the URL is on the same origin as the calling script.
* include: Always send cookies, even for cross-origin calls.

[source](https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials)

If possible, `same-origin` should probably be used.

**Comment by langpavel** [comment]
I will keep include because it's same in this case. And of you move GraphQL endpoint to different domain, you will have hard times of you overlook this :-)

**Pull request merged**
