### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by CombatCode**
Added support to build Docker image based on react-starter-kit

This PR includes:
- Dockerfile
- Bash script to easy build Docker image

Usage:

```
chmod +x scripts/build_docker.sh
./scripts/build_docker.sh
```

### CODE REVIEW

**Comment by CombatCode** [comment]
Travis tests fail is not related with this PR

**Comment by kevinsimper** [comment]
Could you rerun travis?

Also i think you should replace `build_docker.sh` with a docker-compose.yml file :)

**Comment by cuzzo** [comment]
@kevinsimper this might be what you're looking for: https://github.com/kriasoft/react-starter-kit/pull/403 [=

**Comment by langpavel** [comment]
`Dockerfile` already added

**Pull request closed without merging**
