### PR TITLE
TRACKING: master → feature/react-intl

### PR DESCRIPTION
**Pull request by langpavel**
This will not be closed. This is tracking PR for keeping feature branches in sync:

See #1084 — `master` → `feature/redux`
See #1135 — `feature/redux` → `feature/react-intl`

### CODE REVIEW

**Comment by dnson** [comment]
@langpavel could you please help me resolve these conflict?

**Comment by langpavel** [comment]
@dnson Yeah.. there was more changes.. I must sync all feature branches because this is last in chain master → feature/redux → feature/apollo → feature/react-intl..

**Comment by langpavel** [comment]
@dnson I will wait until #1277 will be merged.

**Comment by alopes** [comment]
Are there any plans to fix this? I'm struggling to merge feature/react-intl with master. Thanks

**Pull request closed without merging**
