### PR TITLE
Made Component Generator script

### PR DESCRIPTION
**Pull request by pranaygp**
I thought It'd be an awesome idea to have a script that generates new components for you. So I implemented this basic bash script that generates boilerplate code when you wanna create a new component in your project.

I made a script and a npm helper command that calls the bash script
## To create a new Component

The `new.sh` script is located in the `src/components` directory

``` bash
$ ./new.sh OUTPUT_DIRECTORY COMPONENT_NAME
```
#### Example

``` bash
$ ./new.sh . Slider
```

If you are in the root directory of your project, there's a npm helper script declaration. So, you can run

``` bash
$ npm run new -- COMPONENT_NAME
```
#### Example

``` bash
$ npm run new -- Slider
```
## Output

Using the script will create a new directory in Components with this structure:

```
├── /COMPONENT_NAME                    # The source code of the application
│   ├── /package.json                  # Contains version number, component name and main file
│   ├── /COMPONENT_NAME.js             # Imports for RSK classes, empty render method, export
│   ├── /COMPONENT_NAME.scss           # Blank stylesheet
```

---

This change is [Reviewable](https://reviewable.io/reviews/kriasoft/react-starter-kit/443)

### CODE REVIEW

**Comment by Bogdaan** [comment]
@pranaygp +1 great feature, but you aproach works only no *nix.
For example, my generator (see https://github.com/Bogdaan/react-auth-kit/blob/master/tools/generate.js) works on windows and osx. And work with template (https://github.com/Bogdaan/react-auth-kit/blob/master/tools/templates/component/Component.js)

**Comment by russbeye** [comment]
@pranaygp, like @Bogdaan said, it's a great idea. I think Bogdaan has a more robust path moving forward, and I hope that his implementation (or something like that) can be merged in. Great work though!

**Comment by koistya** [comment]
Would do you think about writing it in JavaScript? This way it would work cross-platform and maybe easier to tweak by people not familiar with shell programming. This script could be executed like this:

```sh
$ node tools/createComponent VideoPlayer
$ node tools/createRoute ProductPage
```

**Comment by pranaygp** [comment]
Hey, 

That works for me. I might take a stab at it sometime this weekend, unless you want to do it yourself? 

Cheers

**Comment by koistya** [comment]
@pranaygp that would be awesome, thanks!

**Comment by stupidisum** [comment]
https://github.com/kriasoft/react-starter-kit/pull/508
 @koistya  @pranaygp 
I've done this for you guys.
Thanks for @Bogdaan

**Comment by ulani** [comment]
@deslee thank you very much for this PR! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Pull request closed without merging**
