### PR TITLE
Switch Jade/Lodash to Handlebars, Less to SCSS

### PR DESCRIPTION
**Pull request by joaquingatica**
May be useful for you to create a branch with this libraries instead of the ones you use.

I prefer handlebars over Jade, and SCSS over LESS, and I think a lot of people do.

Hope this helps.

Cheers!

### CODE REVIEW

**Comment by frankleng** [comment]
+1 awesome choices!

**Comment by koistya** [comment]
Yep, good stuff. I would just split Handlebars and SASS into two different customization branches.

**Comment by cmnstmntmn** [comment]
@joaquingatica, i spent almot half a day to switch from less to sass, without luck and i cannot figure what's wrong

`
/Users/ctin/repos/goxgames/build/webpack:/~/style-loader/addStyles.js:24
		if(typeof document !== "object") throw new Error("The style-loader cannot be used in a non-browser environment");
^
Error: The style-loader cannot be used in a non-browser environment
    at module.exports (/Users/ctin/repos/goxgames/build/webpack:/~/style-loader/addStyles.js:24:1)
    at Object.<anonymous> (/Users/ctin/repos/goxgames/build/webpack:/src/components/App/App.scss?59ed:7:1)
    at __webpack_require__ (/Users/ctin/repos/goxgames/build/webpack:/webpack/bootstrap 494259d365f853f9391c:19:1)
    at Object.module.exports.Object.defineProperty.value (/Users/ctin/repos/goxgames/build/webpack:/src/components/App/App.js:3:41)
    at __webpack_require__ (/Users/ctin/repos/goxgames/build/webpack:/webpack/bootstrap 494259d365f853f9391c:19:1)
    at Object.<anonymous> (/Users/ctin/repos/goxgames/build/webpack:/src/server.js:11:33)
    at __webpack_require__ (/Users/ctin/repos/goxgames/build/webpack:/webpack/bootstrap 494259d365f853f9391c:19:1)
    at module.exports._this2 (/Users/ctin/repos/goxgames/build/webpack:/webpack/bootstrap 494259d365f853f9391c:39:1)
    at Object.<anonymous> (/Users/ctin/repos/goxgames/build/webpack:/webpack/bootstrap 494259d365f853f9391c:39:1)
    at Module._compile (module.js:460:26)
`

**Comment by koistya** [comment]
@cmnstmntmn you need to remove `style-loader` from server-side bundle (`build/server.js`) configuration. Take a look here -> [webpack.config.js#L154](https://github.com/kriasoft/react-starter-kit/blob/0cb05a46b272ac300032f464377d8c9b1e9e11eb/webpack.config.js#L154)

**Comment by cmnstmntmn** [comment]
@koistya same error after i removed 

`loader: loader.loader = loader.loader.replace(STYLE_LOADER + '!', '') line from server-side bundle block
 `

`/Users/ctin/repos/gg/build/webpack:/~/style-loader/addStyles.js:24
		if(typeof document !== "object") throw new Error("The style-loader cannot be used in a non-browser environment");
^
Error: The style-loader cannot be used in a non-browser environment
    at module.exports (/Users/ctin/repos/gg/build/webpack:/~/style-loader/addStyles.js:24:1)
    at Object.<anonymous> (/Users/ctin/repos/gg/build/webpack:/src/components/App/App.scss?f7c3:7:1)
    at __webpack_require__ (/Users/ctin/repos/gg/build/webpack:/webpack/bootstrap d05bb9b2a15eceb5ab75:19:1)
    at Object.module.exports.Object.defineProperty.value (/Users/ctin/repos/gg/build/webpack:/src/components/App/App.js:3:41)
    at __webpack_require__ (/Users/ctin/repos/gg/build/webpack:/webpack/bootstrap d05bb9b2a15eceb5ab75:19:1)
    at Object.<anonymous> (/Users/ctin/repos/gg/build/webpack:/src/server.js:11:33)
    at __webpack_require__ (/Users/ctin/repos/gg/build/webpack:/webpack/bootstrap d05bb9b2a15eceb5ab75:19:1)
    at module.exports._this2 (/Users/ctin/repos/gg/build/webpack:/webpack/bootstrap d05bb9b2a15eceb5ab75:39:1)
    at Object.<anonymous> (/Users/ctin/repos/gg/build/webpack:/webpack/bootstrap d05bb9b2a15eceb5ab75:39:1)
    at Module._compile (module.js:460:26)

`

**Comment by cmnstmntmn** [comment]
odd, i copy/paste the content of [webpack.config.jj] (https://github.com/kriasoft/react-starter-kit/blob/0cb05a46b272ac300032f464377d8c9b1e9e11eb/webpack.config.js#L154), 
replace .less with .scss ans less-loader with sass-loader and it works, still test fails

**Comment by korczis** [comment]
:+1:

**Comment by frob** [comment]
The issues deals more to one of choice. I prefer less to scss, maintaining two branches can be burdonsom. It would be better if this was more configurable to allow an easier switch between scss/libsass to postcss to less.

**Comment by koistya** [comment]
@frob in my practice there is very little use of LESS and Sass, since it's better to avoid writing code in .less/.scss files (mixins, loops etc.), but instead write that logic in real programming language - JavaScript, inside React components. This way the code tend to be more maintainable. In this starter kit none of LESS or Sass features are used except for variables, there rest is just pure CSS.

**Comment by frob** [comment]
@koistya I understand and agree with all that. I was simply making the statement that all of this should not be forced by a starter-kit and it should instead be flexible enough to use whatever flavor of css the developer is used to.

Instead of switching from one pre/post css/less/sass/scss flavor, it should be documented as how to switch these at will so the developer is able to use what is right for them and their organization.

**Comment by joaquingatica** [comment]
@koistya Would you mind if I close this pull request? Doesn't make sense any more with all the new versions you've released.

**Comment by koistya** [comment]
@joaquingatica yep, sure.

**Pull request closed without merging**
