### PR TITLE
Add setDescription function in context

### PR DESCRIPTION
**Pull request by fchienvuhoang**
add setDescription to client.js and server.js to active method setDescription in each router:
`state.context.setDescription('some description');`

### CODE REVIEW

**Comment by fchienvuhoang** [comment]
@koistya please check this pull :)

**Comment by frenzzy** [comment]
Why do not you want to use a `context.setMeta('description', 'some description')`?

**Comment by azz0r** [comment]
Agree with the above.

**Comment by fchienvuhoang** [comment]
@frenzzy have you tried with that code ? ins't work
err

**Comment by fchienvuhoang** [comment]
it worked, thanks :)

**Comment by fchienvuhoang** [comment]
because i had not understood below code:
`setMeta: (key, value) => (data[key] = value),`
it ok now :D, 
thanks all

**Pull request closed without merging**
