### PR TITLE
fix babel core usage

### PR DESCRIPTION
**Pull request by reisel**
babel core supports a transformFileSync method which this process would highly benefit from

### CODE REVIEW

**Comment by langpavel** [comment]
What benefits will have sync version over async?

**Comment by reisel** [comment]
this is only on the messages process. this process doesn't apply in dev hot mode.
So this process just simplifies the messages tool.

**Comment by langpavel** [comment]
Oh, got it, thank you very much @reisel, merged

I'm also thinking about moving `messages` dir one level up — to the project root. Do you think that this is good idea?

Next think is new build step I'm thinking about — split messages by chunk and language
This way it should be much more usable directly with webpack, possibly move localization loading to build process instead of runtime as it is handled now...

**Comment by reisel** [comment]
@langpavel hey,
I think moving them to the root folder will be a good choice, they are not really part of the source code.
regarding the splitting to chunks could improve load time, especially for apps with a lot of text.

I'm currently in the process of designing how to add the translations into our workflow.
I think I would use a google spreadsheet divided by source file with all the messages and translation and load them on compile time to build the jsons.

How would you implement the localizations in compile time?
create a different chunk for each supported language?

I really liked the approach of the md files for large texts.

**Pull request merged**
