### PR TITLE
Update how-to-implement-routing.md with first draft of routing descri…

### PR DESCRIPTION
**Pull request by richb-hanover**
…ption

Update package.json to include default fields - name, description, author, version, license
Update humans.txt to mention other technologies

Hope this is useful as a first-cut at documenting routing. (Not sure any of it is true...)

---

This change is [Reviewable](https://reviewable.io/reviews/kriasoft/react-starter-kit/489)

### CODE REVIEW

**Comment by koistya** [comment]
@richb-hanover thanks for the PR! Much appreciated. Please give me some time to review it.

**Comment by richb-hanover** [comment]
Yes, you need to review it carefully, because I really am not sure I understand this yet... Thanks.

**Comment by richb-hanover** [comment]
Updated package.json to include gaze@^1.0.0. This removes deprecations of lodash & graceful-fs. There are no outdated dependencies now; only these warnings during npm install:
````
npm WARN prefer global marked@0.3.5 should be installed with -g
npm WARN prefer global jsonlint@1.6.2 should be installed with -g
npm WARN prefer global colorguard@1.1.0 should be installed with -g
npm WARN prefer global cover@0.2.9 should be installed with -g
````

**Comment by ulani** [comment]
@richb-hanover  thank you very much for this PR! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Pull request closed without merging**
