### PR TITLE
[Babel] Improve the production build

### PR DESCRIPTION
**Pull request by oliviertassinari**
Add some plugins for improving the production build.

| Name | Build size impact | Description |
|:-----|:-----|:------|
| [transform-react-constant-elements](https://babeljs.io/docs/plugins/transform-react-constant-elements/) | 0 kB | Save some memory allocation. |
| [transform-react-inline-elements](https://babeljs.io/docs/plugins/transform-react-inline-elements//) | -1 kB | Improve runtime performances. |
| [transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) *(Promoted)* | -2 kB | Remove `propTypes`. |

---
This change is [Reviewable](https://reviewable.io/reviews/kriasoft/react-starter-kit/440)

### CODE REVIEW

**Comment by Bogdaan** [comment]
@oliviertassinari +1 must-have plugins in build process,  but it is better move this to .babelrc

**Comment by oliviertassinari** [comment]
@koistya Do you want this PR? I can rebase if needed.

**Comment by koistya** [comment]
@oliviertassinari yep, looking good. I will merge.

**Comment by oliviertassinari** [comment]
@koistya Rebased.

**Comment by oliviertassinari** [comment]
@koistya Thanks :tada:.

**Pull request merged**
