### PR TITLE
Add react-helmet to substitute context.setTitle/setMeta

### PR DESCRIPTION
**Pull request by awesomejerry**
By using react-helmet instead of self-implemented setTitle and setMeta, we're able to put more control over head tag.

https://github.com/nfl/react-helmet

### CODE REVIEW

**Comment by joonhocho** [comment]
+1

**Comment by langpavel** [comment]
Helmet is good solution at first look. But when you need to update deeply nested hierarchy of components it can introduce some not cleanly deterministic behaviors. Title and metas should be determined at most higher levels of component hiearchy as possible..

**Comment by rdewolff** [comment]
So we'll keep the current behaviour for now @langpavel ?

**Comment by langpavel** [comment]
Helmet have side effect when (re)rendering component. Helmet allows cascading but this should behave strange when you update component in the middle of hierarchy. I don't know if this is fixed... (Or if this was caused by bad `shouldComponentUpdate` implementation in my code)

So I'm for keeping imperative style for title except someone will proof that using Helmet is really without this unwanted side effects..

**Comment by ulani** [comment]
@awesomejerry  thank you very much for this PR! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Pull request closed without merging**
