### PR TITLE
Introduce Sequelize as ORM.

### PR DESCRIPTION
**Pull request by arkeros**
First of all I want to congratulate @koistya for your excellent work with this project.

Since this project is a "starter kit", it seems reasonable to support more databases such as MySQL or SQLite, and the simplest way to do going to use an ORM. Therefore, I have decided to collaborate and add Sequelize to this project.

Changes I made:
The default database is sqlite to facilitate the development.
Porting Facebook login to use the new database.
A folder 'models' in './src/data' containing the 'User', 'UserLogin', 'UserClaim' and 'UserProfile' models.

This is the first PR I do. Don't be mean to me if I did something wrong :)

---
This change is [Reviewable](https://reviewable.io/reviews/kriasoft/react-starter-kit/534)

### CODE REVIEW

**Comment by arkeros** [comment]
This solves https://github.com/kriasoft/react-starter-kit/issues/334#issuecomment-195697330

**Comment by koistya** [comment]
@arkeros good stuff, much appreciated!

**Comment by 5punk** [comment]
Nice work, thanks a lot for this.
By any chance could you add some documentation here or show how to use so it will be easier for people who want to store data..

@arkeros

**Comment by Jaikant** [comment]
@arkeros  Not sure of the difference between the User and the UserLogin table. The both seem to shows the time when the login was created and last time it was updated (last login time?).

**Pull request merged**
