### PR TITLE
Bootstrap 3

### PR DESCRIPTION
**Pull request by langpavel**
Demo of basic integration of Bootstrap 3

### CODE REVIEW

**Comment by jj117** [comment]
For some reason, the navbar doesn't render in 2x high-density (retina) with this.

**Comment by langpavel** [comment]
@jj117 Thanks for reporting this.. My solution is very naïve, is here mostly for demonstrating how to... There are better ways but I don't have time for this. If you figure this out, please make PR against `feature/bootstrap3` branch

**Comment by justin808** [comment]
@koistya, @jj117, @langpavel, with the solution provided, you do not seem to have access to the sass variables. I'd like to work with you all on integrating https://github.com/shakacode/bootstrap-loader/ with this project. We've had a number of requests in our project to make the two work together. Here's a try: https://github.com/shakacode/react-starter-kit-with-bootstrap-loader/pull/1


CC: @zeyton

**Comment by jj117** [comment]
@langpavel - I think the rendering issue was browser related - unrelated to your pr.

@justin808 - I'll take a look soon

**Comment by langpavel** [comment]
@justin808 Yes, this solution is very primitive. Pull requests against `feature/bootstrap3` branch are welcomed!

**Comment by justin808** [comment]
@langpavel How important is the isomorphic-style-loader to this project? This seems to inline the styles so the browser does not pay attention to the normal classes, and it prevents the browser from caching the style file.

CC: @FakhruddinAbdi

**Comment by priyanshu911** [comment]
[React bootstrap](https://react-bootstrap.github.io/getting-started.html) worked for me.
```<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css" />``` in Html.js

And directly use it any componet ```import { Alert } from 'react-bootstrap;```

`<Alert bsStyle="warning">
		    Hello </Alert>`

**Comment by langpavel** [comment]
isomorphic-style-loader and withStyles are there because of critical CSS paths. They prevents FOUC. With HTTP2 or spdy protocol this shouldn't be issue any more.

**Comment by leviwheatcroft** [comment]
Looks like a few things have changed over the last year..

In the recent versions of `react-starter-kit` you can call `src/copy` with `yarn run copy`, but when you `yarn start` the build folder is cleaned, but `copy` is not run at that time, so copying the bootstrap assets as in this PR doesn't seem to work. As @priyanshuchauhan suggested, using a CDN works (and is pretty much the same thing).

Additionally, when using the `react-bootstrap` version in this PR II was getting a weird `Cannot read property 'bool' of undefined` error which I couldn't track down, but updating to `0.31.5` seems to have resolved that.

**Comment by ulani** [comment]
@langpavel  thank you very much for this PR! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Pull request closed without merging**
