### PR TITLE
Removed unnecessary page load at client boot

### PR DESCRIPTION
**Pull request by d0ntth1nc**

### CODE REVIEW

**Comment by koistya** [comment]
@d0ntth1nc but.. in order to generate a virtual DOM tree, it needs to has access to data from stores.

**Comment by d0ntth1nc** [comment]
I think that we can pass the initial data in script tag with type "application/json" and parse it on the client side without new request, what do you think?

**Comment by koistya** [comment]
This way you won't be ably to enable strict content security policy (CSP)
on your site, right?
>
>

**Comment by d0ntth1nc** [comment]
using json.stringify + json.parse ofc

**Comment by d0ntth1nc** [comment]
im not sure, imma try some stuff

**Comment by d0ntth1nc** [comment]
Здравствуй! I found nice solution... CSP prevents inline scripts, but not hidden divs. JSON is just a string and we can insert it in <div id="initial-data" style="display:none;"></div> tag. On the client side we can do -> var data = JSON.parse(document.getElementById("initial-data").innerHTML);

**Comment by koistya** [comment]
This approach can potentially has an issue with SEO...

**Comment by d0ntth1nc** [comment]
I found a library named "iso". It creates empty div tag and puts all the data in "data-state" attribute. I don`t think that empty div tag will affect SEO. Neither CSP will prevent empty script tag with data-state attribute. :)

**Comment by koistya** [comment]
This could work. I personally use this approach in my projects - all bootstrap / state data is requested simultaneously with the main application bundle:

```html
<script src="/data.js"></script>
<script src="/app.js"></script>
```

**Pull request merged**
