### PR TITLE
Discard comments from CSS in release mode

### PR DESCRIPTION
**Pull request by frenzzy**
discardcomments

### CODE REVIEW

**Comment by koistya** [comment]
I'm not sure that it's legal to remove copyright comments like `/*! normalize.css */`, but I like the `JSON.stringify(..)` pattern!

**Comment by vitaly-t** [comment]
It is not legal. Plus, comments that start with `/*!` are special and mean `do not remove!`

**Comment by Bogdaan** [comment]
I agree, but you notice that the lince-comments of npm/js libs dont included in the build?
Мany devs include this information in the LICENSE file.

**Comment by Bogdaan** [comment]
for example normalize.css copyright (LICENSE) is https://github.com/necolas/normalize.css/blob/master/LICENSE.md

Comments in source files (and build result) is not a copyright, or I'm wrong?

**Comment by koistya** [comment]
What @vitaly-t said ^^ Merged with `discardComments: { removeAll: true }` line removed.

**Pull request merged**
