### PR TITLE
Update babel and webpack packages

### PR DESCRIPTION
**Pull request by bodia-uz**
- Updated babel and webpack packages to latest.
- Added [.babelrc](http://babeljs.io/blog/2015/03/31/5.0.0/#babelrc) (equivalent to JSHint's .jshintrc and JSCS' .jscsrc.)
- Changed deprecated babel [playgorund](http://babeljs.io/blog/2015/03/31/5.0.0/#removed-features) option with [stage=0](https://babeljs.io/blog/2015/03/31/5.0.0/#stage-0:-class-properties) option.

### CODE REVIEW

**Comment by koistya** [comment]
Thanks. Looks good! Unfortunately `babel-eslint` is not yet compatible with `babel 5.x`. Maybe we should wait for an update? Otherwise there will be lots of validation errors during a build: `gulp build --verbose`

**Comment by bodia-uz** [comment]
Ok. So lets wait for an update https://github.com/babel/babel-eslint/issues/61

**Comment by koistya** [comment]
@bodia-uz can you please include an updated babel-eslint 3.0.1 into your commit?

**Comment by bodia-uz** [comment]
If You do not need it urgently, I will include it tomorrow.

Вт, 14 квіт. 2015 10:10 Konstantin Tarkus <notifications@github.com> пише:

**Comment by koistya** [comment]
Thanks, merged!

**Pull request closed without merging**
