### PR TITLE
Pure Apollo integration based on `master`

### PR DESCRIPTION
**Pull request by piglovesyou**
Pure Apollo integration based on `master`.

## Features

* TypeScript implementation that Apollo primarily supports
* `apollo-client` with full server-side rendering - No `fetch()`
* Client-side state management with `apollo-client@2.5` with `networkStatus` example
* `apollo-server` serves GraphQL API
* Codegen Flow types - Flow type checking follows GraphQL Schema
* More Flow Types - More confident use of component properties
* GraphQL Scalar type - `Timestamp` for an example

## Branches

* Master: [piglovesyou:feature/apollo-pure](https://github.com/piglovesyou/react-starter-kit/tree/feature/apollo-pure)
* Stable: [kriasoft:feature/apollo-pure](https://github.com/kriasoft/react-starter-kit/tree/feature/apollo-pure)

### CODE REVIEW

**Comment by langpavel** [comment]
Hi! Great work, I will review it in my rare free time :slightly_smiling_face:
Will be great if you prepare new PR which I can merge to master with updated README
— added link to `feature/apollo-pure` branch which I can create from this PR.

Please remind me in few days if I forget to do it :wink:

**Comment by piglovesyou** [comment]
@langpavel Thank you for your support. I did on #1665 .

**Comment by langpavel** [comment]
Your work is now pushed in [`feature/apollo-pure` branch](https://github.com/kriasoft/react-starter-kit/tree/feature/apollo-pure)

**Comment by piglovesyou** [comment]
@langpavel Wow, pleasure, thanks.

Then shall I delete this PR? Further commits and discussion seem to go in https://github.com/kriasoft/react-starter-kit/pull/1666.

**Comment by langpavel** [comment]
Don't delete this PR, you can push fresh commits here.
I believe that you can open new PRs against `feature/apollo-pure` branch from commits on top of this branch.

**Comment by piglovesyou** [comment]
All right. I'll push another to it when I feel like it.

**Comment by tim-soft** [comment]
I should probably get around to fixing issues with the apollo branch... per field resolvers and apollo server 2.0

**Comment by langpavel** [comment]
Please, mention me every time, I'm not watching issues very often… thanks :slightly_smiling_face:

**Comment by tim-soft** [comment]
@langpavel and babel v7 :)

**Comment by piglovesyou** [comment]
@langpavel I have a question. When I'd like to update `kreasoft:feature/apollo-pure`, I need to create a PR on it every time, is that correct? I'm thinking publishing another feature like apollo codegen.

**Comment by piglovesyou** [comment]
Sorry I missed your previous comment, I'll create a PR to react-starter-kit:feature/apollo-pure.

**Comment by piglovesyou** [comment]
I think I can close this PR now. I'll keep maintaining `feature/apollo-pure` on #1666.

**Pull request closed without merging**
