### PR TITLE
Azure deployment

### PR DESCRIPTION
**Pull request by koistya**
Allows to deploy the site to [Azure Web Apps](http://azure.microsoft.com/services/app-service/web/)
##### How to merge it to your project

``` shell
$ git checkout -b azure master
$ git pull https://github.com/koistya/react-starter-kit.git azure
$ git checkout master
$ git merge --no-ff azure
```
##### How to deploy

(1) Open your Web App in [Azure portal](https://portal.azure.com). (2) Enable Git-based deployment from a local Git repository. (3) Copy and paste Git repository from Azure portal to the `tools/deploy.js` file. Then you can simply run:

``` shell
$ npm run deploy
```

[azure-app-service](http://azure.microsoft.com/services/app-service/)

### CODE REVIEW

**Comment by koistya** [comment]
#### Microsoft Azure Tips, Tricks, How Tos and the New Portal - TechDaysUK Hanselman Keynote

[img](http://www.youtube.com/watch?v=DASqJEs1NiQ)

**Comment by lehneres** [comment]
What is the benefit of this script? Pushing the build folder rightaway to Azure seems to work the same.

**Comment by martin-jujou-sirca** [comment]
What about deployment to other services like amazon? Is it possible to make this system deployable to S3 somehow (looks like currently its very node based)

**Comment by KraigWalker** [comment]
I wouldn't say this script is entirely suitable. It would work, but it leverages Azure's default assumption of in-place deployment. Getting Kudu to do a full production build within the Web App sandbox to eliminate the possibility of any side-effects from the committer's local machine.

**Pull request closed without merging**
