### PR TITLE
Redux integration

### PR DESCRIPTION
**Pull request by langpavel**
Base Redux integration.

Some development is still in progress

Ref #173

### CODE REVIEW

**Comment by langpavel** [comment]
@koistya Can you review please? I'm still working but commited code will not change.

**Comment by koistya** [comment]
Pavel, thanks for your PR. Much appreciated! I think we can merge it into `[feature/redux](https://github.com/kriasoft/react-starter-kit/tree/feature/redux)` branch for now.

FYI, the `App` component is most likely be renamed to `Layout`.. and everything that is not related to the layout, e.g. StylesProvider, ReduxStoreProvider will need to be moved somewhere else, maybe into the root (top-level) route..

**Comment by langpavel** [comment]
@koistya Hi. Now I'm missing root HoC, good point!
There should be one place to add `Provider` and similar root level third party HoC.
Do you implement this or should I try it?
Layout is too late I thing :-)

**Comment by koistya** [comment]
I haven't settled yet on how it should look like, you can give it a try.. feel free to ping me on Skype (s: koistya) if you need to discuss anything.

**Comment by langpavel** [comment]
@koistya How I can change PR target to `feature/redux`? Can you merge this by hand or I should open new PR?

**Comment by koistya** [comment]
@langpavel merged manually to the [`feature/redux`](https://github.com/kriasoft/react-starter-kit/compare/feature/redux) branch. Great stuff!

**Comment by langpavel** [comment]
Thanks!

**Pull request closed without merging**
