### PR TITLE
Use TypeScript and other improvements on feature/apollo-pure

### PR DESCRIPTION
**Pull request by piglovesyou**
* TypeScript support and non-typed module declaration
* Make codegen always able to run
* Use default client state management in apollo-client and remove apollo-link-state
* refac: make all components functional

### CODE REVIEW

**Comment by piglovesyou** [comment]
@langpavel I turned it to TypeScript. Glad if you take a look.

**Comment by langpavel** [comment]
I'm out of time this week, please, remind me if I forget :-) Thanks!
BTW If you wish help with universal-router, here is my PR: https://github.com/kriasoft/universal-router/pull/166

**Comment by piglovesyou** [comment]
> TS universal-router
Cool. I'll use your types after it's merged and released.

**Comment by piglovesyou** [comment]
@langpavel Ready. Glad if you take time.

**Comment by piglovesyou** [comment]
Thank you Pavel!

**Pull request merged**
