### PR TITLE
A bare minimum Redux integration

### PR DESCRIPTION
**Pull request by koistya**
#### Next steps
- Register your application store reducers in [`core/createStore.js`](https://github.com/koistya/react-starter-kit/blob/redux/src/core/createStore.js)
- Decorate your React components that need to read data from the store with `connect(..)` middleware from the [`react-redux`](https://github.com/reactjs/react-redux) package

#### For more information visit
- http://redux.js.org/docs/basics/UsageWithReact
- http://redux.js.org/docs/recipes/ServerRendering
- https://medium.com/horrible-hacks/things-i-wish-i-knew-about-redux-9924abf2f9e0

#### How to Merge
```sh
git checkout -b redux master
git pull https://github.com/koistya/react-starter-kit.git redux
git checkout master
git merge redux
```

Ref #753, #738, #612, #173.

### CODE REVIEW

**Comment by joshuamanns** [comment]
This should be the default setup for RSK, in my opinion. Passing data from server to client feels sloppy without at least a minimum redux store such as this.

**Comment by jwhchambers** [comment]
Hi @koistya, thanks for all the hard work on this project! I have a quick question regarding this PR. In the react-intl branch, the initial state is assigned using the following:
```
        {script && (
          <script
            id="source"
            src={script}
            data-initial-state={JSON.stringify(state)}
          />
        )}
``` 
However, in this PR, you serialize it instead of stringify:
```
        {state && <script
          dangerouslySetInnerHTML={{
            __html: `window.APP_STATE=${serialize(state, { isJSON: true })}`,
          }}
        />}
        {script && <script src={script} />}
```
Then both methods fetch it in client.js. I can see how both work, I was just wondering if there is a preferred approach and what the pros/cons are? Many thanks!

**Comment by amilajack** [comment]
This would be great. @koistya what is the status of this?

**Comment by koistya** [comment]
@jwhchambers deserializing data from a `data-` attribute on the client might be an expensive operation, on the other hand, if you embed data inside the <script> tag, you need to make sure that you don't expose XSS vulnerability.

**Comment by langpavel** [comment]
I just Integrated this into `feature/redux` and `feature/react-intl`

**Comment by ulani** [comment]
@koistya  thank you very much for this PR! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Pull request closed without merging**
